## 1. Setup

In [18]:
import pandas as pd
import numpy as np

## 2. Loading data

In [ ]:
# Loading the dataset
df = pd.read_csv('../Data/dataset.csv')
df.head()

,sku_id,retailer,country,sku_name_eng,description_short_eng,breadcrumbs_eng,sku_url,image_url,sku_last_price,gtin,brand,category,attribute
0,6916,Walmart,USA,"Concord Foods, Smoothie Banana Drink Mix, 2 oz",""""" \n* Smoothie, Banana \n* Just Add: 1 ripe b...","["""" Food"""","""" Beverages"""","""" Powdered Drink Mi...",https://www.walmart.com/ip/Concord-Foods-Smoot...,https://i5.walmartimages.com/seo/Concord-Foods...,5.77,NaN,by Concord Foods,Powder Concentrates,Free From: no allergens; Weight: 57; Flavour: ...
1,12782,Rite Aid,USA,"Sierra Mist Soda, Lemon- Lime, 12 fl oz - 12 ct",With other natural flavors. No artificial ingr...,"["""" Shop"""","""" Household"""","""" Food, Snacks & Ca...",https://www.riteaid.com/shop/sierra-mist-soda-...,https://www.riteaid.com/shop/media/catalog/pro...,6.11,1.200023e+10,Sierra Mist,Lemonade/Lime,"Water Type: soda; Flavour: lemon, lime; Volume..."
2,16627,peapod,USA,Teavana Passion Tango Craft Herbal Iced Tea,Teavana Craft Iced Herbal Tea Passion Tango . ...,"["""" Beverages"""","""" Ready To Drink Tea""""]",https://www.peapod.com/,https://i5.peapod.com/c/K6/K6RMM.jpg,2.49,1.820026e+10,Teavana,Still RTD Tea,Sweetener: sugar; Pack Material Type: Glass; C...
3,19126,Ocado,United Kingdom,Brecon Carreg Still Water,Nestled in the beautiful Brecon Beacons Nation...,"["""" Soft Drinks, Tea & Coffee"""","""" Water""""]",https://www.ocado.com/webshop/product/Brecon-C...,https://www.ocado.com/productImages/450/450760...,0.65,NaN,Brecon Carreg,Still Bottled Water,Juice Content: 0-2%; Pack Material Type: Plast...
4,27474,Publix,USA,Zephyrhills 100% Natural Spring Water,ZEPHYRHILLS Brand 100% Natural Spring Water ha...,"["""" Beverages"""","""" Water, Seltzer & Sparkling ...",https://delivery.publix.com/store/items/41529659,https://d2lnr5mha7bycj.cloudfront.net/product-...,1.53,NaN,Zephyrhills,Carbonated Bottled Water,Volume: 3000; Water Type: spring; Naturally de...

## 3. Feature processing

In [ ]:
# Collecting attributes and their values for each sku_id
storage = {}
attributes = []

# Iterating through each row in the dataframe
for index, row in df.iterrows():
    # Collecting the sku_id and attributes for each row
    sku_id = row['sku_id']
    attribute_list = row['attribute'].split(';')

    # Iterating through each attribute in the attribute_list of each row
    for attribute in attribute_list:
        # Collecting attribute name and its value
        attribute_name = attribute.split(':')[0].strip()
        attribute_value = attribute.split(':')[1].strip()

        # If name is unique, add it to the attributes list
        if attribute_name not in attributes:
            attributes.append(attribute_name)

        # Append attribute and its value to the storage dictionary for each sku_id
        if sku_id not in storage:
            storage[sku_id] = {}
        storage[sku_id][attribute_name] = attribute_value

# Removing attribute column from the dataframe
df.drop(columns=['attribute'], inplace=True)

# Creating new columns for each unique attribute and populating them with their corresponding values
for attribute in attributes:
    df[attribute] = df['sku_id'].apply(lambda x: storage[x].get(attribute, np.nan))

# Dropping columns with cosntant values
df = df.drop(columns=['Special Edition', 'Giftbox'])

df.to_csv('../Data/testing.csv', index=False)    
df.head()

,sku_id,retailer,country,sku_name_eng,description_short_eng,breadcrumbs_eng,sku_url,image_url,sku_last_price,gtin,...,Geographic Origin,RTD Coffee Style,Coffee Type,Energy Source,Sports Drinks Style,Environmentally Friendly,Sports Positioning,Roast Type,Special Edition,Giftbox
0,6916,Walmart,USA,"Concord Foods, Smoothie Banana Drink Mix, 2 oz",""""" \n* Smoothie, Banana \n* Just Add: 1 ripe b...","["""" Food"""","""" Beverages"""","""" Powdered Drink Mi...",https://www.walmart.com/ip/Concord-Foods-Smoot...,https://i5.walmartimages.com/seo/Concord-Foods...,5.77,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12782,Rite Aid,USA,"Sierra Mist Soda, Lemon- Lime, 12 fl oz - 12 ct",With other natural flavors. No artificial ingr...,"["""" Shop"""","""" Household"""","""" Food, Snacks & Ca...",https://www.riteaid.com/shop/sierra-mist-soda-...,https://www.riteaid.com/shop/media/catalog/pro...,6.11,1.200023e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16627,peapod,USA,Teavana Passion Tango Craft Herbal Iced Tea,Teavana Craft Iced Herbal Tea Passion Tango . ...,"["""" Beverages"""","""" Ready To Drink Tea""""]",https://www.peapod.com/,https://i5.peapod.com/c/K6/K6RMM.jpg,2.49,1.820026e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19126,Ocado,United Kingdom,Brecon Carreg Still Water,Nestled in the beautiful Brecon Beacons Nation...,"["""" Soft Drinks, Tea & Coffee"""","""" Water""""]",https://www.ocado.com/webshop/product/Brecon-C...,https://www.ocado.com/productImages/450/450760...,0.65,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,27474,Publix,USA,Zephyrhills 100% Natural Spring Water,ZEPHYRHILLS Brand 100% Natural Spring Water ha...,"["""" Beverages"""","""" Water, Seltzer & Sparkling ...",https://delivery.publix.com/store/items/41529659,https://d2lnr5mha7bycj.cloudfront.net/product-...,1.53,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN